theme: jekyll-theme-minimal
title: "Tab2Onto: Unsupervised Semantification with Knowledge Graph Embeddings"
logo: /assets/Tab2Onto-logo.png
description:
show_downloads: true
repository: dice-group/Tab2Onto
