theme: jekyll-theme-minimal
title: "Unsupervised Semantification with Knowledge Graph Embeddings"
author: Data Science Group, Paderborn University
logo: /assets/Tab2Onto-logo.png
description:
show_downloads: false
baseurl: /Tab2Onto
repository: dice-group/Tab2Onto
